### PR TITLE
Support for the 2in7 E-Paper Display

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
Doesn't allow 4-gray scale yet 
Only 2 color (Black/White) is supported

### CODE REVIEW

**Comment by VedantParanjape** [comment]
Hi, thankyou for your contribution. I will review this code and let you know a few fixes.

Do you have a 2.7" inch display to test this code?

**Comment by Kaiserdragon2** [comment]
> Hi, thanks for your contribution. I will review this code and let you know a few changes.
> 
> Do you have a 2.7" inch display to test this code?
> 
> 

Yes I have the 2.7" inch display and I have testet this code.

**Comment by VedantParanjape** [comment]
Hi @Kaiserdragon2 this supports only 2.7 inch D version, can you change variable names to match that, in config.h, Kconfig and everywhere else.

**Comment by Kaiserdragon2** [comment]
The 2.7" inch Display has only two versions and this is the 2.7" inch and the 2.7"(B) inch version.
This code is for the 2.7"inch version. Therefore I have already changed the variables.
Or do I get something wrong and you mean something else ?

**Comment by VedantParanjape** [comment]
My bad, just checked you are right, I was confused as the comment in source file said 2.7"inch D display

You are using some different source code, can you port the .cpp file from here: https://github.com/waveshare/e-Paper/tree/master/Arduino/epd2in7

**Comment by Kaiserdragon2** [comment]
I have ported the code from your given source and change the comment to the right display.

**Review by VedantParanjape — APPROVED** [review]

**Comment by VedantParanjape** [comment]
Thanks for your contribution, I have merged the PR. Please verify once again that this works and let me know.

**Comment by Kaiserdragon2** [comment]
Tested the Code after merging and it works fine.

**Comment by VedantParanjape** [comment]
Cool

**Pull request merged**
